/**
 * BootScene.ts
 * First Phaser scene. Sets rendering settings and immediately advances to PreloadScene.
 *
 * Responsibilities:
 * - Configure Phaser rendering settings (pixelArt, antialias = false).
 * - Start the PreloadScene.
 */

export class BootScene extends Phaser.Scene {
  constructor() {
    super({ key: 'BootScene' });
  }

  preload(): void {
    // No assets to load in Boot — everything is procedurally generated by SE2
  }

  create(): void {
    // Ensure pixel-art rendering is enforced
    this.cameras.main.setBackgroundColor('#000000');

    // Hand off to PreloadScene
    this.scene.start('PreloadScene');
  }
}
